/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ObjetosDB.*;
import java.awt.Cursor;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ttars
 */
public class frameNuevaPromo extends javax.swing.JFrame {
    
    
    DefaultTableModel modelo = new DefaultTableModel();
  ArrayList<Productos> lista =new   ArrayList<Productos>();
    /**
     * Creates new form frameNuevaPromo
     */ 
    public frameNuevaPromo() throws SQLException {
        initComponents();metodosDB metodos = new metodosDB();
             lista= new metodosDB().getProductos();
             
             
                       Collections.sort(lista, new Comparator<Productos>(){

			@Override
			public int compare(Productos o1, Productos o2) {
				return o1.getNombre().compareTo(o2.getNombre());
			}
			
			
		});  
             
             
              for(int k=0;k<lista.size();k++){
                  if(metodos.getPromosIdProducto(lista.get(k).getId_producto())!=0){
                                         this.jComboBox1.addItem(lista.get(k).getNombre()+" "+lista.get(k).getTalla()+" "+lista.get(k).getMedida()+ " ID: "+lista.get(k).getId_producto());

                  }
              }
             
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INGRESE NUEVA PROMOCIÓN");

        jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(41, 91, 134));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/disk.png"))); // NOI18N
        jButton1.setText("Guardar Promoción");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/arrow_undo.png"))); // NOI18N
        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Descuento ($) :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Producto:");

        jButton4.setText("Agregar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("TOTAL ($) :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // TODO add your handling code here:
            int error = 0;
         int selected=jComboBox1.getSelectedIndex()  ; 
            
             //OBETENER ID PARA PROMO
            metodosDB metodos = new metodosDB();
           int idpromo2= metodos.getLastId("promociones")+1;
            System.out.println(idpromo2);
          for(int i=0;i<jTable2.getRowCount();i++){
              
              
              //SE CREA PROMOCION CON SU ID PERO EL PRIMARY KEY ES PRODUCTO YA QUE NO SE PUEDE REPETIR EN UNA PROMOCION
              System.out.println("VEAMOS:");
              String idproducto=this.jTable2.getValueAt(i, 0).toString();   System.out.println("id:"+idproducto);
              System.out.println(this.jTable2.getValueAt(i, 1).toString());
              System.out.println(this.jTable2.getValueAt(i, 2).toString());
                   Promociones promo = new Promociones(idpromo2,Integer.parseInt(jTextField3.getText()),Integer.parseInt(idproducto),(int)jTable2.getValueAt(i, 3));
      
   metodos.addPromo(promo);
          }
            
            
            if (error == 0)
                    JOptionPane.showMessageDialog(rootPane,  "Promoción creada exitosamente");
                dispose();
        } catch (SQLException ex) {
            Logger.getLogger(frameNuevaPromo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
 String t[] = {"ID", "NOMBRE","PRECIO VENTA","CANTIDAD"};

        modelo.setColumnIdentifiers(t);
        jTable2.setModel(modelo);
        DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
        DefaultTableCellRenderer tcr2 = new DefaultTableCellRenderer();
        tcr2.setHorizontalAlignment(SwingConstants.CENTER);
        tcr.setHorizontalAlignment(SwingConstants.RIGHT);
          jTable2.getColumn("ID").setPreferredWidth(5);
        jTable2.getColumn("NOMBRE").setPreferredWidth(30);
           jTable2.getColumn("PRECIO VENTA").setPreferredWidth(30);
        jTable2.getColumnModel().getColumn(0).setCellRenderer(tcr);
        jTable2.getColumnModel().getColumn(1).setCellRenderer(tcr);
        jTable2.getColumnModel().getColumn(2).setCellRenderer(tcr2);
        ((DefaultTableCellRenderer) jTable2.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
    
        jTable2.setRowHeight(22);
        jTable2.setCellSelectionEnabled(false);
        jTable2.setRowSelectionAllowed(true);
 
        
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            
		     String nombre=jComboBox1.getSelectedItem().toString();
           /*   System.out.println(nombre);
              jComboBox1.removeItemAt(jComboBox1.getSelectedIndex());*/
             
                
                     
                     
                     
                          for(int k=0;k<lista.size();k++){
                           String nombre2=lista.get(k).getNombre()+" "+lista.get(k).getTalla()+" "+lista.get(k).getMedida()+ " ID: "+lista.get(k).getId_producto(); 
                      int m=0;
                           boolean existe=false;
                           if(nombre2.indexOf(nombre)!=-1){
                               
                               //BUSCAR SI EXISTE PRODUCTO
                               int rows= jTable2.getRowCount();
                               while(m<rows){
                                   
                                   if(lista.get(k).getId_producto()==jTable2.getValueAt(m, 0)){
                                      int cantidad= Integer.parseInt(jTable2.getValueAt(m, 3).toString());
                                       jTable2.setValueAt(cantidad+1, m, 3);
                                       existe=true;
                                         this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)); 
                                      double imp=0;
        if(lista.get(k).getHarina()==0){
                imp=  (double) (lista.get(k).getPrecioVenta()*1.0);
                    System.out.println(imp);
           int var2 = (int) Math.ceil(imp);
              
                    
            
            }else{
               imp=  (double) (lista.get(k).getPrecioVenta()*1.31);
                    System.out.println(imp);
           int var2 = (int) Math.ceil(imp);
              
                  
            }   
                                         
            int suma=  Integer.parseInt(  jLabel4.getText())+(int)imp ; 
               jLabel4.setText(Integer.toString(suma));
                                   }
                                   m++;
                               }
                               
                               //SI EXISTE SUMAR CANTIDAD SI NO AGREGAR
                               if(existe==false){
                                     System.out.println(nombre);
                           System.out.println(nombre2);               // System.out.println("hola");                      
 Object[] object = new Object[4];
                    
       //SETEAR PRODUCTO PARA AGREGAR A JTABLE
        object[0] = lista.get(k).getId_producto();
        object[1] = lista.get(k).getNombre();
        
        double imp=0;
        if(lista.get(k).getHarina()==0){
                imp=  (double) (lista.get(k).getPrecioVenta()*1.0);
                    System.out.println(imp);
           int var2 = (int) Math.ceil(imp);
              
                    
                   object[2] =(int)imp;
            }else{
               imp=  (double) (lista.get(k).getPrecioVenta()*1.31);
                    System.out.println(imp);
           int var2 = (int) Math.ceil(imp);
              
                    object[2] =(int)imp;
            }
                
                object[3]=1;
            int suma=  Integer.parseInt(  jLabel4.getText())+(int)imp ;
                jLabel4.setText(Integer.toString(suma));
         modelo.addRow(object);  
         this.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR)); 
                               }
                                   
                          
                              
                              
                              
                              }
                              
                              
                              
                          }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameNuevaPromo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameNuevaPromo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameNuevaPromo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameNuevaPromo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frameNuevaPromo().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(frameNuevaPromo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
