/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Clases.funciones;
import ObjetosDB.OrdenDeVenta;
import ObjetosDB.metodosDB;
import java.awt.Cursor;
import java.awt.Desktop;
import java.io.File;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;

/**
 *
 * @author tars
 */
public class frameCuadrarCaja extends javax.swing.JFrame {
    DefaultTableModel modelo= new DefaultTableModel(); // Tabla Productos

    /**
     * Creates new form frameCuadrarCaja
     */
    public frameCuadrarCaja() {
        initComponents();
        iniciar();
    }
    public void iniciar()
    {
        String t3[] = {"ID","Numero Boleta","Monto","Fecha","Medio Pago","Cliente"};
        modelo.setColumnIdentifiers(t3);
        jTable1.setModel(modelo);
        jLabel2.setText(getFecha());
        int suma =0;
        try {
            ArrayList<OrdenDeVenta> ordenesDia = new metodosDB().getVentasDia(getFecha(),end());
            for(OrdenDeVenta orden: ordenesDia)
            {
            Object[] object = new Object[6];
            object[0] = orden.getIdOrdenVenta();
            object[1] = orden.getNumeroBoleta();
            object[2] = orden.getMontoTotal();
            object[3] = orden.getFecha();
            object[4] = orden.getMedioPago();
            object[5] = orden.getCliente().getNombre();
            modelo.addRow(object);
            suma = suma + Integer.parseInt(orden.getMontoTotal());


            
            }
            jLabel4.setText(Integer.toString(suma));
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Error en la Base de Datos"); 
        }
        
        

    }
     private String getFecha()
 {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd 13:00:00");
        Calendar cal = Calendar.getInstance();
        String FechaHoy = dateFormat.format(cal.getTime());
        return FechaHoy;
 }
         private String end()
 {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd 03:59:59");
        Calendar cal = Calendar.getInstance();
        cal.add( Calendar.DATE, 1 );
        String FechaHoy = dateFormat.format(cal.getTime());
        return FechaHoy;
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CUADRAR CAJA");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/arrow_undo.png"))); // NOI18N
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Ventas del día : ");

        jLabel2.setText("jLabel2");

        jLabel3.setText("Total Caja ($):");

        jLabel4.setText("jLabel4");

        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Export To Document.png"))); // NOI18N
        jButton5.setText("ARCHIVO");
        jButton5.setToolTipText("");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(45, 45, 45)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     try {
     if(modelo.getRowCount()==0){
                      jframe1 a = new jframe1();
            JOptionPane.showMessageDialog(a, "NO EXISTEN VENTAS ASOCIADAS AL DIA SELECCIONADO");
            return ;
               }
    
    ArrayList<OrdenDeVenta> ordenesDia = null;
 
              String date2=jLabel2.getText().replaceAll("/", "-");
              String date1=jLabel2.getText().replaceAll("/", "-");
            ordenesDia = new metodosDB().getVentasDia(date2.trim(),end());
            this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
            
            funciones f = new funciones();
            File proveedores = new File(f.getRutaExcel() + "Cuadratura Caja"+date1+".xls");
            WritableWorkbook workbook = Workbook.createWorkbook(new File(f.getRutaExcel() + "Cuadratura Caja"+date1+".xls"));
            //Se crea una nueva hoja dentro del libro
            WritableSheet sheet = workbook.createSheet("CUADRATURA DIARIA", 1);
            sheet.setColumnView(1, 15);
            sheet.setColumnView(2, 17);
            sheet.setColumnView(3, 17);
            sheet.setColumnView(4, 17);
            sheet.setColumnView(5, 18);
            sheet.setColumnView(6, 17);
             int i=0;
             int suma=0;
            for ( i = 0; i < modelo.getRowCount(); i++) {
              
                if (i == 0) { 
                    sheet.addCell(new jxl.write.Label(1, 4, "ID VENTA"));
                      sheet.addCell(new jxl.write.Label(2, 4, "FECHA"));
                    sheet.addCell(new jxl.write.Label(3, 4, "MONTO TOTAL"));
                    sheet.addCell(new jxl.write.Label(4, 4, "NUMERO BOLETA"));
                    sheet.addCell(new jxl.write.Label(5, 4, "MEDIO PAGO"));
                    sheet.addCell(new jxl.write.Label(6, 4, "NOMBRE CLIENTE."));
                }
                   
             
                sheet.addCell(new jxl.write.Label(1, i + 5, jTable1.getValueAt(i, 0).toString()));
                sheet.addCell(new jxl.write.Label(2, i + 5,jTable1.getValueAt(i, 1).toString()));
                sheet.addCell(new jxl.write.Label(3, i + 5, jTable1.getValueAt(i, 2).toString()));
                sheet.addCell(new jxl.write.Label(4, i + 5,jTable1.getValueAt(i, 3).toString()));
                sheet.addCell(new jxl.write.Label(5, i + 5, jTable1.getValueAt(i, 4).toString()));
                    sheet.addCell(new jxl.write.Label(6, i + 5, jTable1.getValueAt(i, 5).toString()));
            }
                sheet.addCell(new jxl.write.Label(6,  i + 6, "MONTO NETO TOTAL."));
                sheet.addCell(new jxl.write.Label(6, i + 7,jLabel4.getText() ));
            workbook.write();
            workbook.close();
            this.setCursor(Cursor.getDefaultCursor());
            if (Desktop.isDesktopSupported() == true) {
                Desktop desktop = Desktop.getDesktop();
                try {
                    desktop.open(proveedores);
                    return;
                } catch (Exception ex) {
                     JOptionPane.showConfirmDialog(null, "" + ex.getMessage(), "ERROR2", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

        } catch (Exception ex) {
            this.setCursor(Cursor.getDefaultCursor());
             JOptionPane.showConfirmDialog(null, "" + ex.getMessage(), "ERROR1", JOptionPane.PLAIN_MESSAGE, JOptionPane.ERROR_MESSAGE);
            return;
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
